import type { Metadata } from "next";
import "./globals.css";
import { Roboto_Mono as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import NavBarCom from "@/components/NavBar/NavBarCom";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "</DEVSM>",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={cn(
          "min-h-screen bg-[#f2f2f2] font-sans antialiased p-5 max-w-[1440px] m-auto",
          fontSans.variable
        )}
      >
        <NavBarCom />
        <div className="flex flex-cols py-5">{children}</div>
      </body>
    </html>
  );
}
