import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";

import { cn } from "@/lib/utils";
import NavBarCom from "@/components/NavBar/NavBarCom";
import ProfileCardCom from "@/components/Main/ProfileCardCom";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "DEVSM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={cn(
          "min-h-screen bg-[#f2f2f2] font-sans antialiased p-5",
          fontSans.variable
        )}
      >
        <NavBarCom />
        <div className="flex flex-cols py-5">
          {/* <ProfileCardCom /> */}
          {children}
        </div>
      </body>
    </html>
  );
}
